${"user_name_code".toCamelNaming}
${"User_name_code".toCamelNaming}
${"_user_name_code".toCamelNaming}
${"user_name_code_".toCamelNaming}
${"_user_name_code_".toCamelNaming}
${"UserNameCode".toCamelNaming}
${"userNameCode".toCamelNaming}
----
${"user_name_code".toCapitalNaming}
${"User_name_code".toCapitalNaming}
${"_user_name_code".toCapitalNaming}
${"user_name_code_".toCapitalNaming}
${"_user_name_code_".toCapitalNaming}
${"userNameCode".toCapitalNaming}
${"UserNameCode".toCapitalNaming}
----
${"userNameCode".toUnderlineNaming}
${"UserNameCode".toUnderlineNaming}
${"user_name_code".toUnderlineNaming}
${"_user_name_code".toUnderlineNaming}
${"user_name_code_".toUnderlineNaming}
${"_user_name_code_".toUnderlineNaming}
