${template.name}
${this.template.name}
${this.this.template.name}
${this.super.template.name}
${this.super.super.template.name}
${super.template.name}
${super.this.template.name}
${super.super.template.name}
${super.super.this.template.name}
----
$embed{"../included/scope_a.ctl"}