${null/null}
${null/"abc"}
${"abc"/null}
${"aaa.bbb.ccc"/"."}
${".aaa.bbb.ccc"/"."}
${"aaa.bbb.ccc.."/"."}
${".aaa.bbb.ccc."/"."}
${"...aaa.bbb.ccc"/"."}
${"aaa.bbb.ccc..."/"."}
${"...aaa...bbb.ccc..."/"."}
${"...aaa...bbb.ccc..."/"..."}
${"...abc...abc.abc..."/"abc"}
