$data{"properties"}
mail.from=xxx@xxx.com
mail.to=yyy@yyy.com
employees.0.id=1
employees.0.name=james
employees.1.id=2
employees.1.name=kent
$end
${mail.from}
${employees[0].name}
${employees[1].id}